apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: team1-gateway
spec:
  selector:
    istio: istio-ingressgateway.istio-system.svc.cluster.local
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: counter
spec:
  gateways:
  - team1-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
      prefix: /api/team1
    route:
    - destination:
        host: backend
        port:
          number: 9898