apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: counter
spec:
  gateways:
  - istio-ingressgateway.istio-system.svc.cluster.local
  hosts:
  - '*'
  http:
  - match:
    - uri:
      prefix: /api/team1
    route:
    - destination:
        host: backend
        port:
          number: 9898