apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: team1-frontend
spec:
  gateways:
  - istio-system/ingressgateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
      prefix: /
    route:
    - destination:
        host: frontend
        port:
          number: 9898